sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: uOC76YpLTChihSYXcdDjdQWgZ3gP3cgsgWbvzy4eCl31B5xMPAyqE5j89HUW9OxTlixYoMGTP/Htbmqt9+NM77+vavrPiE5N20nyTZHo1NCud/CwE2Uxe3KjxGPCli4gT2axE6H2PFveDsrvfd2+T2Eq2rv4vqsgxqT23LrEMwhcUP9dmTLdYigw46KFnT2kWejDHdnU/CtTu0W3QOeSZNSFAPVR1GuhCvT6HZTYih841KHw0CZOgmL5y/j0Al2nLc1Dr+Izq+n/7pqcOfBFj45nH59VLdrS4f5w4j5SNZk6cEANM31npENGaLURSt2/9OsnOAhU6WIkLwF9BY+UMGic9UfQZZm4QhdHZHc47VX+PECFGFpiUlwzL8rqHMzrn5ymhA/8RhmXNP0nk3dMLumK3upS/GcX3Bj3+0zfkQArZ0h+68P+H/wJ0Y4/KVBqyEc0pDp6Dqk3F0m0dHIiBlsAnoBvhR/PNT4fRmhRDi4S3nJZRQ/lMUaRSmmNB0aZgRL8p0ubcR3f82x74IHWE8hDwMHK5fbyJSoKaI06KK52sNeqaDPwih/G6FSNdXbHTjPZI+DQaJkO2p2avxC9JDnQgHMLQZmEMbkUOFXXi5nemqdt2GVgsKQA+lctOHLTBemyeDVgwTv9VYn/4eiF/PCF1RyDggnLxl9wH6KXuLs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/State-of-the-Union-Addresses_5025
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy